src/Entity/Dette.php
<?php

namespace App\Entity;

use App\Repository\DetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DetteRepository::class)]
class Dette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Le Montant est obligatoire', groups: ['controller'])]
    private ?float $montant = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Entrer un premier montant')]
    private ?float $montantVerser = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $dateAt = null;

    #[ORM\ManyToOne(inversedBy: 'dettes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private bool $archived = false;

    /**
     * @var Collection<int, Paiement>
     */
    #[ORM\OneToMany(targetEntity: Paiement::class, mappedBy: 'dette', cascade: ['persist', 'remove'])]
    private Collection $paiements;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'La Quantité est obligatoire')]
    private ?float $Qte = null;

    /**
     * @var Collection<int, Articles>
     */
    #[ORM\ManyToMany(targetEntity: Articles::class, inversedBy: 'dette', cascade: ['persist', 'remove'])]
    private Collection $articles;



    public function __construct()
    {
        $this->paiements = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getMontantRestant(): float
    {
        return max(0, $this->montant - $this->montantVerser);
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMontantVerser(): ?float
    {
        return $this->montantVerser;
    }

    public function setMontantVerser(float $montantVerser): static
    {
        $this->montantVerser = $montantVerser;

        return $this;
    }

    public function getDateAt(): ?\DateTimeImmutable
    {
        return $this->dateAt;
    }

    public function setDateAt(\DateTimeImmutable $dateAt): static
    {
        $this->dateAt = $dateAt;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function isArchived(): bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): static
    {
        $this->archived = $archived;

        return $this;
    }

    /**
     * @return Collection<int, Paiement>
     */
    public function getPaiements(): Collection
    {
        return $this->paiements;
    }

    public function addPaiement(Paiement $paiement): static
    {
        if (!$this->paiements->contains($paiement)) {
            $this->paiements->add($paiement);
            $paiement->setDette($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): static
    {
        if ($this->paiements->removeElement($paiement)) {
            // set the owning side to null (unless already changed)
            if ($paiement->getDette() === $this) {
                $paiement->setDette(null);
            }
        }

        return $this;
    }

    public function getQte(): ?float
    {
        return $this->Qte;
    }

    public function setQte(float $Qte): static
    {
        $this->Qte = $Qte;

        return $this;
    }

    /**
     * @return Collection<int, Articles>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Articles $articles): self
    {
        if (!$this->articles->contains($articles)) {
            $this->articles->add($articles);
            $articles->addDette($this);
        }
        return $this;
    }

    public function removeArticle(Articles $articles): self
    {
        if ($this->articles->removeElement($articles)) {
            $articles->removeDette($this);
        }
        return $this;
    }
}

src/Controller/DemandeController.php
<?php

namespace App\Controller;

use App\Dto\DemandeFormSearch;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\DemandeDetteRepository;
use App\Entity\DemandeDette;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Dette;
use App\Entity\Articles;
use App\Form\DemandeFormSearchType;
use Symfony\Component\HttpFoundation\Request;
use App\Form\DemandeDetteType;

class DemandeController extends AbstractController
{
    #[Route('/boutiquier/demandes', name: 'demande.liste')]
    public function listeDemandes(DemandeDetteRepository $demandeDetteRepository, Request $request): Response
    {
        $demandeFormSearch = new DemandeFormSearch();
        $searchDemandeForm = $this->createForm(DemandeFormSearchType::class, $demandeFormSearch);
        $searchDemandeForm->handleRequest($request);

        $page=max(1,$request->query->getInt('page',1));
        $limit=7;
        $demandes = $demandeDetteRepository->findPaginatedDemandeDette($page,$limit);
        $count=$demandes->count();

        $nbrePage=ceil($count/$limit);
        $page = min($page, $nbrePage); 

        if ($searchDemandeForm->isSubmitted() && $searchDemandeForm->isValid()) {
            $surname = $demandeFormSearch->getSurname();
            $demandes = $demandeDetteRepository->searchDemande($surname);
        }


        return $this->render('demande/index.html.twig', [
            'demandes' => $demandes,
            'nbrePage'=>$nbrePage,
            'page'=>$page,
            'searchDemandeForm' => $searchDemandeForm->createView()
        ]);
    }




    #[Route('/client/demandes/{id}', name: 'demande.details')]
    public function detailsDemande(DemandeDette $demande): Response
    {
        return $this->render('demande/details.html.twig', [
            'demande' => $demande,
        ]);
    }






    #[Route('/boutiquier/demandes/{id}/accepter', name: 'demande.accepter')]
    public function accepterDemande(DemandeDette $demande, EntityManagerInterface $entityManager): Response
    {
        $article = $demande->getArticles(); 
        $qteDemandee = $demande->getQte();
    
        // Validation : vérifier que le stock est suffisant
        if ($qteDemandee > $article->getQteStock()) {
            $this->addFlash('danger', 'La quantité demandée dépasse le stock disponible pour l\'article ' . $article->getLibelle());
            return $this->redirectToRoute('demande.details', ['id' => $demande->getId()]);
        }
    
        // Mise à jour du stock
        $article->setQteStock($article->getQteStock() - $qteDemandee);
    
        // Création de la dette
        $dette = new Dette();
        $dette->setClient($demande->getClient());
        $dette->setQte($qteDemandee);
        $dette->setMontant($demande->getMontant());
        $dette->setMontantVerser(0);
        $dette->setDateAt(new \DateTimeImmutable());
    
        // Ajouter l'article à la dette
        $dette->addArticle($article);
    
        // Persist la dette et supprimer la demande
        $entityManager->persist($dette);
        $entityManager->remove($demande);
        $entityManager->flush();
    
        return $this->redirectToRoute('demande.liste');
    }
    
    



    #[Route('/boutiquier/demandes/{id}/refuser', name: 'demande.refuser')]
    public function refuserDemande(DemandeDette $demande, EntityManagerInterface $entityManager): Response
    {
        // Supprimer la demande de la base de données
        $entityManager->remove($demande);
        $entityManager->flush();

    
        // Rediriger vers la liste des demandes
        return $this->redirectToRoute('demande.liste');
    }




    /////////////LISTER POUR CLIENT////////////////////

    #[Route('/client/demandes/{idClient}/client', name: 'demande.index')]
    public function index($idClient, DemandeDetteRepository $demandeDetteRepository, Request $request): Response
    {
        $demandeFormSearch = new DemandeFormSearch();
        $searchDemandeForm = $this->createForm(DemandeFormSearchType::class, $demandeFormSearch);
        $searchDemandeForm->handleRequest($request);

        $page=max(1,$request->query->getInt('page',1));
        $limit=7;
        $demandes = $demandeDetteRepository->findByClientDemandes($idClient,$page,$limit);
        $count=$demandes->count();

        $nbrePage=ceil($count/$limit);
        $page = min($page, $nbrePage); // Pas plus que le nombre total de pages

        if ($searchDemandeForm->isSubmitted() && $searchDemandeForm->isValid()) {
            $surname = $demandeFormSearch->getSurname();
            $demandes = $demandeDetteRepository->searchDemande($surname);
        }


        return $this->render('demande/index.html.twig', [
            'demandes' => $demandes,
            'nbrePage'=>$nbrePage,
            'page'=>$page,
            'searchDemandeForm' => $searchDemandeForm->createView()
        ]);
    }




    ////////CREER DETTE////////////////////

    #[Route('/demandes/create', name: 'demande.create')]
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $demande = new DemandeDette();
        $user = $this->getUser();
    
        // Si l'utilisateur est un client, associer automatiquement le client
        if (in_array('ROLE_CLIENT', $user->getRoles())) {
            $client = $user->getClient();
            $demande->setClient($client);
        }
    
        $form = $this->createForm(DemandeDetteType::class, $demande);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $demande->setDateAt(new \DateTimeImmutable());
    
            // Calculer le montant
            $article = $demande->getArticles();
            $montant = $article->getPrix() * $demande->getQte();
            $demande->setMontant($montant);
    
            $entityManager->persist($demande);
            $entityManager->flush();
    
            // Redirection conditionnelle
            if (in_array('ROLE_BOUTIQUIER', $user->getRoles())) {
                return $this->redirectToRoute('demande.liste');
            } elseif (in_array('ROLE_CLIENT', $user->getRoles())) {
                $client = $user->getClient();
                if ($client) {
                    return $this->redirectToRoute('demande.index', ['idClient' => $client->getId()]);
                }
            }
    
            return $this->redirectToRoute('app_home');
        }
    
        return $this->render('demande/form.html.twig', [
            'formDemande' => $form->createView(),
        ]);
    }
    

}

templates/demande/details.html.twig
{% extends 'base.html.twig' %}

{% block main %}

	<!-- Titre -->
	<!-- mt-4=1rem, mb-9=2.25rem, px-4=1rem -->
		<div class="container" style="margin-top:3rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;"> <div
			class="d-flex justify-content-between align-items-center">
			<!-- text-3xl=1.875rem, font-semibold -->
			<h2 class="fw-semibold text-black" style="font-size:1.875rem;">Détails de la demande</h2>
		</div>
	</div>


	<!-- Information -->

	<div class="container" style="margin-top:2rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div
			class="d-flex justify-content-between align-items-center">
			<!-- text-3xl=1.2rem, font-semibold -->
			<h2 class="fw-semibold text-primary" style="font-size:1.3rem;">Informations</h2>
		</div>
	</div>

	<div class="container" style="margin-top:-1rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div class="d-flex align-items-center justify-content-start flex-wrap" style="gap: 24.9rem;">
			<div class="d-flex align-items-center">
				<h2 class="fw-semibold text-black" style="font-size:1rem; margin: 0;">Client :</h2>
				<p class="fw-normal text-black" style="margin: 0; margin-left: 0.5rem;">
					{{ demande.client.surname }}
				</p>
			</div>
			<div class="d-flex align-items-center">
				<h2 class="fw-semibold text-black" style="font-size:1rem; margin: 0;">Article :</h2>
				<p class="fw-normal text-black" style="margin: 0; margin-left: 0.5rem;">
					{{ demande.articles.libelle }}
				</p>
			</div>
		</div>
	</div>

	<div class="container" style="margin-top:-1rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div class="d-flex align-items-center justify-content-start flex-wrap" style="gap: 20rem;">
			<div class="d-flex align-items-center">
				<h2 class="fw-semibold text-black" style="font-size:1rem; margin: 0;">Quantité demandée :</h2>
				<p class="fw-normal text-black" style="margin: 0; margin-left: 0.5rem;">
					{{ demande.qte }}
				</p>
			</div>
			<div class="d-flex align-items-center">
				<h2 class="fw-semibold text-black" style="font-size:1rem; margin: 0;">Montant :</h2>
				<p class="fw-normal text-black" style="margin: 0; margin-left: 0.5rem;">
					{{ demande.montant }}
				</p>
			</div>
		</div>
	</div>

	<div class="container" style="margin-top:-1rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div class="d-flex align-items-center justify-content-start flex-wrap" style="gap: 20rem;">
			<div class="d-flex align-items-center">
				<h2 class="fw-semibold text-black" style="font-size:1rem; margin: 0;">Stock actuel :</h2>
				<p class="fw-normal text-black" style="margin: 0; margin-left: 0.5rem;">
					{{ demande.articles.qteStock }}
				</p>
			</div>
		</div>
	</div>

	<!-- Affichage des messages d'alerte -->
	<div class="container d-flex justify-content-center align-items-center" style="margin-top:2rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div class="d-flex justify-content-between align-items-center">
			{% for type, messages in app.flashes %}
				<div class="alert alert-{{ type }}">
					{% for message in messages %}
						{{ message }}
					{% endfor %}
				</div>
			{% endfor %}
		</div>
	</div>


{% if is_granted('ROLE_BOUTIQUIER') %}

	<div class="container" style="margin-top:-1rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
		<div class="d-flex align-items-center justify-content-start flex-wrap" style="gap: 20rem;">
			<div class="d-flex align-items-center">
				<a href="{{ path('demande.accepter', { id: demande.id }) }}" class="btn btn-success">Accepter</a>
				<a href="{{ path('demande.refuser', { id: demande.id }) }}" class="btn btn-danger ms-3">Refuser</a>
			</div>
		</div>
	</div>

{% endif %}


{% endblock %}

templates/demande/form.html.twig
{% extends 'base.html.twig' %}

{% block main %}

	<!-- Titre -->
	<div class="container text-center" style="margin-top:3rem; margin-bottom:2.25rem;">
		<h2 class="fw-semibold text-black mb-5" style="font-size:1.875rem;">Nouvelle Demande de Dette</h2>
		<h3 id="montantTotal" class="fw-semibold text-primary" style="font-size:1.5rem;">Montant Total : 0</h3>
	</div>

	<!-- Form -->
	<div class="container px-1 mb-4" style="max-width: 900px; margin: 0 auto;">
		<div class="mb-5">
			{{ form_start(formDemande) }}
			{% if app.user and 'ROLE_BOUTIQUIER' in app.user.roles %}
				{{ form_row(formDemande.client) }}
			{% endif %}
			{{ form_row(formDemande.articles, {
    'attr': {
        'data-prix': formDemande.articles.vars.choices|map(c => c.data.id ~ ':' ~ c.data.prix)|join(',')
    }
}) }}

			{{ form_row(formDemande.qte) }}
			{{ form_row(formDemande.save) }}
			{{ form_end(formDemande) }}

		</div>
	</div>



	<script>
    document.addEventListener('DOMContentLoaded', function () {
        const articlesField = document.querySelector('#demande_dette_articles'); // Sélecteur pour le champ des articles
        const qteField = document.querySelector('#demande_dette_qte'); // Sélecteur pour le champ de quantité
        const montantTotalDisplay = document.querySelector('#montantTotal'); // Affichage du montant total

        // Parse les données des prix depuis l'attribut data-prix
        const prixArticles = {};
        const dataPrix = articlesField.dataset.prix;
        dataPrix.split(',').forEach(pair => {
            const [id, prix] = pair.split(':');
            prixArticles[id] = parseFloat(prix);
        });

        // Fonction pour calculer le montant total
        function calculateMontantTotal() {
            const selectedOption = articlesField.value; // ID de l'article sélectionné
            const qte = parseFloat(qteField.value) || 0; // Quantité saisie

            let total = 0;

            if (prixArticles[selectedOption]) {
                total = prixArticles[selectedOption] * qte; // Calculer le montant total
            }

            montantTotalDisplay.textContent = `Montant Total : ${total.toFixed(2)}`;
        }

        // Écouter les changements sur les champs articles et quantité
        articlesField.addEventListener('change', calculateMontantTotal);
        qteField.addEventListener('input', calculateMontantTotal);
    });
</script>


{% endblock %}

templates/demande/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}

<!-- Titre -->
<!-- mt-4=1rem, mb-9=2.25rem, px-4=1rem -->
	<div class="container" style="margin-top:3rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;"> <div
		class="d-flex justify-content-between align-items-center">
		<!-- text-3xl=1.875rem, font-semibold -->
		<h2 class="fw-semibold text-black" style="font-size:1.875rem;">Liste des Demandes de dette</h2>
		{% if is_granted('ROLE_CLIENT') %}

			<button class="bg-white text-black border border-gray-400 rounded-lg" style="padding:0.5rem 1rem;">
				<a href="{{ path ("demande.create")}}" class="text-black text-decoration-none">Enregistrer</a>
			</button>

		{% endif %}
	</div>
</div>


{% if is_granted('ROLE_BOUTIQUIER') %}

	<!-- Filtrer par -->
	<div class="container" style="margin-top:1rem; margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem; margin-left:10rem;">
		<div class="d-flex justify-content-between align-items-center">
			{{ form_start(searchDemandeForm, { 'attr': {'class': 'w-100'} }) }}

			<!-- Ligne pour afficher les champs sur la même ligne -->
			<div class="row">
				<div class="col">
					{{ form_row(searchDemandeForm.surname, {'label': false, 'attr': {'placeholder': 'Entrer le Surname du Client'}}) }}
				</div>
				<div class="col" style="margin-right:21rem;">
					{{ form_row(searchDemandeForm.rechercher) }}

					{{ form_end(searchDemandeForm) }}
				</div>
			</div>

			{{ form_end(searchDemandeForm) }}
		</div>
	</div>

{% endif %}


<!-- Tableau -->
<!-- mb-9=2.25rem, px-4=1rem -->
<div class="container" style="margin-bottom:2.25rem; padding-left:1rem; padding-right:1rem;">
	<div class="bg-gray-100" style="overflow:hidden; border-radius:0.5rem;">
		<table style="width:100%; table-layout:fixed;">
			<thead class="bg-gray-100">
				<tr>
					<th style="padding:0.5rem 1rem; text-align:left;">Date</th>
					<th style="padding:0.5rem 1rem; text-align:left;">Nom & Prénoms</th>
					<th style="padding:0.5rem 1rem; text-align:left;">S.Client</th>
					<th style="padding:0.5rem 1rem; text-align:left;">Montant</th>
					<th style="padding:0.5rem 1rem; text-align:left;">Action</th>
				</tr>
			</thead>
			<tbody>
				{% for demande in demandes %}
					<tr style="background-color:white;">
						<td style="padding:0.5rem 1rem;">{{demande.dateAt|date('d-m-Y')}}</td>
						<td style="padding:0.5rem 1rem;">
							{% if demande.client.user %}
								{{demande.client.user.nom}}
								{{demande.client.user.prenom}}
							{% else %}
								Pas de Compte
							{% endif %}
						</td>
						<td style="padding:0.5rem 1rem;">{{demande.client.surname}}</td>
						<td style="padding:0.5rem 1rem;">{{demande.montant}}</td>
						<td style="padding:0.5rem 1rem;">
							<a href="{{ path ("demande.details",{id:demande.id})}}" class="fw-semibold" style="color:blue; text-decoration:none;">Détails</a>
						</td>
					</tr>
				{% else %}
					No demande have been found.
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<!-- Pagination -->
<div class="container d-flex justify-content-center" style="margin-bottom:1rem; padding-left:1rem; padding-right:1rem;">
	<div
		class="d-flex" style="column-gap:0.5rem;">
		<!-- Bouton Précédent -->
		<button class="focus-outline-none" style="background-color:#f7fafc; color:#4b5563; border:none; border-radius:9999px; padding:0.25rem 0.75rem;" {% if page > 1 %} onclick="window.location.href='?page={{ page - 1 }}'" {% else %} disabled {% endif %}>
			<span>&lt;</span>
		</button>

		<!-- Boutons de numéros de page -->
		{% for i in 1..nbrePage %}
			<button class="focus-outline-none {{ i == page ? 'active' : '' }}" style="background-color:#f7fafc; color:#1f2937; border:none; border-radius:9999px; padding:0.25rem 0.75rem;">
				<a href="?page={{ i }}" class="text-black text-decoration-none">{{ i }}</a>
			</button>
		{% endfor %}

		<!-- Bouton Suivant -->
		<button class="focus-outline-none" style="background-color:#f7fafc; color:#4b5563; border:none; border-radius:9999px; padding:0.25rem 0.75rem;" {% if page < nbrePage %} onclick="window.location.href='?page={{ page + 1 }}'" {% else %} disabled {% endif %}> <span>&gt;</span> </button> </div> </div> {% endblock %}